Repository GavrilenkoGeorgi/artviva-frontend, pull requests merged in 2020-08, with the labels that each got.

#51 Updated views
  public/manifest.json
  src/Routes.jsx
  src/components/forms/LoginForm.jsx
  src/components/forms/TeacherForm.jsx
  src/components/forms/components/Checkbox.jsx
  src/components/help/SchoolExplained.jsx
  src/components/navigation/NavigationBar.jsx
  src/components/navigation/SchoolSectionsNav.jsx
  src/components/payments/TeacherPaymentsList.jsx
  src/components/pupils/Pupil.jsx
  src/components/pupils/PupilsList.jsx
  src/components/schoolClasses/GroupsList.jsx
  src/components/specialties/SpecialtiesList.jsx
  src/components/specialties/Specialty.jsx
  src/components/teachers/Teacher.jsx
  src/components/teachers/TeacherDetails.jsx
  src/components/users/UserDetailsCard.jsx
  src/components/views/ContactsView.jsx
  src/components/views/GroupsView.jsx
  src/components/views/PupilsView.jsx
  src/components/views/ShowcaseView.jsx
  src/components/views/TeacherPaymentsView.jsx
  src/components/views/TeachersView.jsx
  src/components/views/UserProfileView.jsx
  src/components/views/index.js
  src/components/views/school/Specialties.jsx
  src/css/style.css
  src/css/style.css.map
  src/sass/_fonts.sass
  src/sass/_palette.scss
  src/sass/style.sass
Labels: correction, enhancement

#52 Fix build warings
  src/components/views/TeachersView.jsx
Labels: correction

#53 Text corrections
  src/components/forms/RegisterForm.jsx
  src/data/formTexts.json
  src/data/teachers.json
Labels: typos or missing data

#54 Fix netlify redirect
  public/_redirects
  src/components/forms/UserEditForm.jsx
  src/components/views/UserProfileView.jsx
Labels: bug

#58 Prices and specialties explained view
  package.json
  public/img/departments/bilohorodka/bilohorodka.jpg
  src/Routes.jsx
  src/components/forms/PaymentForm.jsx
  src/components/forms/PupilForm.jsx
  src/components/navigation/NavigationBar.jsx
  src/components/payments/PaymentsList.jsx
  src/components/payments/TeacherPaymentsList.jsx
  src/components/prices/Benefits.jsx
  src/components/prices/Conditions.jsx
  src/components/prices/Prices.jsx
  src/components/prices/index.js
  src/components/views/PricesView.jsx
  src/components/views/UserProfileView.jsx
  src/components/views/index.js
  src/css/style.css
  src/css/style.css.map
  src/data/forms/pupilFields.json
  src/reducers/pupilsReducer.js
  src/reducers/userReducer.js
  src/sass/_text.sass
  src/services/specialties.js
  src/utils/notificationSetter.js
Labels: correction, enhancement

#59 Fix modal not closing
  src/components/forms/GroupForm.jsx
  src/components/forms/PupilForm.jsx
  src/components/specialties/SpecialtiesList.jsx
  src/components/teachers/TeacherDetails.jsx
  src/components/views/GroupsView.jsx
  src/components/views/PupilsView.jsx
Labels: correction

#63 Updated user list, fix user edit form
  src/components/forms/LoginForm.jsx
  src/components/forms/UserEditForm.jsx
  src/components/navigation/NavigationBar.jsx
  src/components/payments/PaymentDescr.jsx
  src/components/payments/TeacherPaymentsList.jsx
  src/components/users/UserDetailsCard.jsx
  src/components/views/CommonLayout.jsx
  src/components/views/ListOfTeachers.jsx
  src/components/views/TeacherPaymentsView.jsx
  src/components/views/UsersListView.jsx
  src/css/style.css
  src/css/style.css.map
  src/data/forms/pupilFields.json
  src/data/forms/teacherFields.json
  src/data/teachers.json
  src/sass/style.sass
Labels: bug, correction

#69 Fixes and updates
  .github/workflows/jest-tests.yml
  src/components/forms/TeacherForm.jsx
  src/components/teachers/TeacherDetails.jsx
  src/components/teachers/TeacherInfo.jsx
  src/components/views/SchoolOverview.jsx
Labels: bug

#68 Generation of pdf from the html data
  .gitignore
  package-lock.json
  package.json
  src/Routes.jsx
  src/components/pupils/Pupil.jsx
  src/components/pupils/PupilDetails.jsx
  src/components/pupils/PupilFormF1.jsx
  src/components/pupils/index.js
  src/components/views/index.js
  src/css/style.css
  src/css/style.css.map
  src/sass/_palette.scss
  src/sass/components/f1Form.sass
  src/sass/style.sass
  src/services/pupils.js
Labels: enhancement

#70 Fix pupil list
  package.json
  src/components/pupils/PupilFormF1.jsx
  src/components/pupils/PupilsList.jsx
  src/components/views/PupilsView.jsx
  src/hooks/scrollHooks.js
Labels: enhancement

#71 Fix public apply form
  package.json
  src/components/forms/PupilForm.jsx
  src/components/pupils/PublicApplyStatus.jsx
  src/components/views/CommonLayout.jsx
  src/components/views/PublicApplyView.jsx
  src/sass/_icons.sass
Labels: bug

#74 More videos and missing teacher descr added
  src/components/views/ShowcaseView.jsx
  src/data/teachers.json
Labels: typos or missing data
